### PR TITLE
Add testing capabilities and travis support

### PR DESCRIPTION
**Pull request by marcfreiheit**
### Testing
This PR introduces the testing framework junit and configured Travis support. All tests can be found in `src/test/java/de/hpi/bpt/scylla/` and must have the `Tests` postfix. The postfix is mandatory, otherwise tests which lack this postfix will be skipped.

### Local Maven Repository
In addition, I've added a local maven repo to manage all plugins. You can find the repo in `src/main/resources/scylla-repository/`. I've included StatsLogging and InterfaceTesting already.
Doing that, you don't have to include the jars manually. You can just pull the code and go ahead. 

### Refactored main method of Scylla
I've refactored the main class in order that it's testable. You can now pass parameters to the main method using the following schema:
```
Usage: Scylla --config=<your config file> --bpmn=<your first bpmn file> [--bpmn=<your second bpmn file>] [--bpmn=...] --sim=<your first sim file> [--sim=<your second sim file>] [--sim=...] [--output=<your output path>]
```
We could consider choosing a better layout. That's just my first try.

### Git LFS
Since .jar-files should't be version controlled, because they are large binary files, I've activated git lfs to keep the repo clean. Git LFS is limited in storage and bandwith and we have to check if our current limits are exhaustive. If not, we have to purchase more storage and bandwith or skip git lfs and disable it.  

## Reladed Issues

- Currently, the functionality isn't tested completely. That's because I can't run some scenarios (Issue #9).  
- #7 should be marked as done (at least partially done) when this pull request is merged. 

## Steps to test or reproduce
Execute `mvn '-Dtest=de.hpi.bpt.scylla.*Tests' test` from the project directory to run all tests. That's the command executed by travis, too. 

## Impacted Areas in Application
List general components of the application that this PR will affect:
* Scylla.jar
* New test files
* Some new files in the root directory (travis, .gitignore, .gitattributes, ...)

## To Do
- [x] Fix issue #9 and test if nothing broke with these changes 
- [ ] Enable Travis for your project at [travis-ci.org](travis-ci.org)
- [ ] Maybe we should move all local dependencies which can be found in `lib/` to the local maven repository or reference them another way. Maybe some of the libraries can be found on github? Then we could add them as [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?
- [ ] @marcfreiheit Add readme for all changes
- [ ] @marcfreiheit Configure the testing framework that all test are executed when running `mvn clean test`. Don't know, why it's not working yet.
- [ ] We can consider setting up [Code Climate](https://codeclimate.com/) in a next step to keep good quality of the source code.
- [ ] @marcfreiheit Finish all tests

### CODE REVIEW

**Comment by marcfreiheit** [comment]
Can we close this pull request without merging it? It seems that it's not of interest? 😀

**Comment by LeonBein** [comment]
Actually it is of interest, I just have not had the time yet to handle it and it seems like Björn has built a little JUnit test. We can discuss this later or simply force push to another branch if necessary.

**Comment by marcfreiheit** [comment]
Copy that. If you've got any questions, please let me know.

**Comment by LeonBein** [comment]
Finally looking into this.
Todo:
- [ ] Merge both gitignores as both have been improved
- [ ] Remove vscode configuration files
- [ ] Are both junit and junit jupiter dependencies needed? (In pom)
- [ ] StatsLogger.jar and InterfaceTesting have been removed, update pom

**Comment by LeonBein** [comment]
I think currently everything is ok, except I am not yet sure how to include the maven dependencies. I moved them to the local maven repository, but that requires them to be installed there manually. I will have to figure something out, especially regarding the plugin structure of Scylla.

**Pull request merged**
